### ISSUE TITLE
Device Manager Not Working on Windows Arm64

### ISSUE THREAD

**Issue by ofoacimr** [ARM-software/vscode-device-manager#6] opened 2024-02-23 14:31 UTC
Type: Bug Report

**Describe the bug**

- OS and Version: Windows 11 Pro (**ARM64**), 23H2, Build 22635.3209; Running on ThinkPad X13s Gen 1, Snapdragon 8cx Gen 3
- VS Code Version: 1.86.2, arm64 version
- Extension Version: v1.10.0
- Target Device: DAPLink, HDSC HC32F030
- Other extensions you installed: Arm Keil Studio Pack v1.13.0 (pre-release), arm64 version
- `Error running command device-manager.####: command 'device-manager.####' not found. This is likely caused by the extension that contributes device-manager.####.`

**To Reproduce**

1. Go to 'Activity Bar' in VS Code
2. Click on 'Device Manager'
3. Click the Button 'Refresh Devices'
```
Error running command device-manager.refresh: command 'device-manager.refresh' not found. This is likely caused by the extension that contributes device-manager.refresh.
```

1. Go to 'Activity Bar' in VS Code
2. Click on 'Device Manager'
3. Click the Button 'Add Device' (the one besides the refresh button, **not** the blue one)
```
Error running command device-manager.addDevice: command 'device-manager.addDevice' not found. This is likely caused by the extension that contributes device-manager.addDevice.
```

1. Go to 'Activity Bar' in VS Code
2. Click on 'Device Manager'
3. Click the Button 'Add Device' (the blue one, **not** the one besides the refresh button)
4. No response

**Expected behavior**

1. Go to 'Activity Bar' in VS Code
2. Click on 'Device Manager'
3. Click the Button 'Add Device'
4. The Command Palette appears, showing what's connected to choose from.

**Code sample and logs**
- Code sample: nothing, the bug persists without any code.
- log: nothing, the extension doesn't work at all, so **it does not show in 'OUTPUT' panel** for logging.

**Screenshots**

![image_2024-02-23_22-21-28](https://github.com/ARM-software/vscode-device-manager/assets/42085166/9e8414d4-b120-4ec2-8560-84c685e2775b)

**Additional context**

1. I carefully compared this extension on Windows arm64 & x64 platform, and it is the same on every line of code.
2. It works perfectly on Windows 11 x64.
3. Disabling other extensions doesn't help.
4. As this extension does not work, I cannot further test whether other Arm Keil Studio extensions are working as expected.

**Comment by ofoacimr** [comment] 2024-02-23 14:58
Additional information:

Under `%USERPROFILE%\.vscode\extensions\arm.device-manager-1.10.0\node_modules\usb\prebuilds\`, there's only win32-ia32 and win32-x64, no arm64 binary for Windows.

**Comment by thegecko** [comment] 2024-02-24 00:04
Thanks for your feedback @ofoacimr 

You are right, there isn't a prebuilt binary for node-usb, so I've added one:

https://github.com/node-usb/node-usb/pull/735

Unfortunately I don't have access to a windows Arm machine to test this works, would you be able to?

You can grab the binary from the `win32-arm64.zip` artefact from the build here:

https://github.com/node-usb/node-usb/actions/runs/8026472128

**Comment by ofoacimr** [comment] 2024-02-24 09:00
Thanks for your support @thegecko 

I found the log, and there're several issues to solve.

This is the startup log with original extensions. → [VS Code Startup.log](https://github.com/ARM-software/vscode-device-manager/files/14392180/VS.Code.Startup.log)

It reports two errors:

1. **[error]** spawn `%USERPROFILE%\.vscode\extensions\arm.keil-studio-pack-1.13.0-win32-arm64\tools\armlm\bin\armlm.exe` **ENOENT**
This is caused by the lack of file extension `.exe` for `armlm`, I think it should be reported to [ARM-software/vscode-keil-studio-pack](https://github.com/ARM-software/vscode-keil-studio-pack). 🤣🤣🤣

2. **[error]** Activating extension 'Arm.device-manager' failed: No native build was found for `platform=win32 arch=arm64 runtime=electron abi=118 uv=1 armv=8 libc=glibc node=18.17.1 electron=27.2.3`
loaded from: `%USERPROFILE%\.vscode\extensions\arm.device-manager-1.10.0\node_modules\@serialport\bindings-cpp`
So, this comes to [serialport/bindings-cpp](https://github.com/serialport/bindings-cpp), it lacks Win32-arm64 prebuilt binary.

As the startup process stopped without loading `node-usb`, adding the binary you built won't change the log. → [VS Code Startup with arm64 USB.log](https://github.com/ARM-software/vscode-device-manager/files/14392220/VS.Code.Startup.with.arm64.USB.log)

Finally, renaming that `armlm` to `armlm.exe` could simply solve the first error. → [VS Code Startup with arm64 USB & armlm.exe.log](https://github.com/ARM-software/vscode-device-manager/files/14392226/VS.Code.Startup.with.arm64.USB.armlm.exe.log)

**Comment by thegecko** [comment] 2024-02-24 22:10
Thanks for your continued feedabck @ofoacimr 

> [error] spawn %USERPROFILE%\.vscode\extensions\arm.keil-studio-pack-1.13.0-win32-arm64\tools\armlm\bin\armlm.exe ENOENT
This is caused by the lack of file extension .exe for armlm, I think it should be reported to [ARM-software/vscode-keil-studio-pack](https://github.com/ARM-software/vscode-keil-studio-pack). 🤣🤣🤣

Yes, this is indeed a problem in the pack. @mcgordonite @federicobozzini could you investigate?

> [error] Activating extension 'Arm.device-manager' failed: No native build was found for platform=win32 arch=arm64 runtime=electron abi=118 uv=1 armv=8 libc=glibc node=18.17.1 electron=27.2.3
loaded from: %USERPROFILE%\.vscode\extensions\arm.device-manager-1.10.0\node_modules\@serialport\bindings-cpp
So, this comes to [serialport/bindings-cpp](https://github.com/serialport/bindings-cpp), it lacks Win32-arm64 prebuilt binary.

PR here: https://github.com/serialport/bindings-cpp/pull/167

Interim binary can be found on this run: https://github.com/thegecko/bindings-cpp/actions/runs/8031265251

**Comment by ofoacimr** [comment] 2024-02-25 06:49
Thanks a lot! @thegecko 

The Device Manager now works properly.

![image](https://github.com/ARM-software/vscode-device-manager/assets/42085166/207c3985-7892-4b01-bb21-c376f0fc5f1f)

However, some other extensions in Arm Keil Studio Pack do not function well under Windows Arm64, and I will report under corresponding Repository.

Thank you again for your fast and professional support!

**Comment by federicobozzini** [comment] 2024-02-26 09:28
> Thanks for your continued feedabck @ofoacimr
> 
> > [error] spawn %USERPROFILE%.vscode\extensions\arm.keil-studio-pack-1.13.0-win32-arm64\tools\armlm\bin\armlm.exe ENOENT
> > This is caused by the lack of file extension .exe for armlm, I think it should be reported to [ARM-software/vscode-keil-studio-pack](https://github.com/ARM-software/vscode-keil-studio-pack). 🤣🤣🤣
> 
> Yes, this is indeed a problem in the pack. @mcgordonite @federicobozzini could you investigate?

I think the problem comes from the fact that when the pack was created the `armlm` binary was not available for Windows on the arm64 architecture. I'll check with the licensing team to see if it's till the case.

**Comment by thegecko** [comment] 2024-07-06 10:50
Can we close this issue @federicobozzini ?

**Comment by federicobozzini** [comment] 2024-08-01 10:35
> Can we close this issue @federicobozzini ?

Unfortunately not. As of the latest version of `armlm` (1.31.1) there is still not version for Windows on the arm64 architecture.

**Comment by thegecko** [comment] 2024-08-13 11:00
> Unfortunately not. As of the latest version of armlm (1.31.1) there is still not version for Windows on the arm64 architecture.

The new error is with the environment manager extension, can this issue be moved there?

**Closed as completed** 2024-12-21 14:40 UTC
Labels: bug
